export interface MultipleSelectListProps {
  fontFamily?: string;
  setSelected: (selected: any) => void;
  placeholder?: string;
  boxStyles?: any;
  inputStyles?: any;
  dropdownStyles?: any;
  dropdownItemStyles?: any;
  dropdownTextStyles?: any;
  maxHeight?: number;
  data: { key: any; value: any; disabled?: boolean }[];
  searchicon?: boolean | React.ReactNode;
  arrowicon?: boolean | React.ReactNode;
  closeicon?: boolean | React.ReactNode;
  search?: boolean;
  searchPlaceholder?: string;
  onSelect?: () => void;
  label?: string;
  notFoundText?: string;
  disabledItemStyles?: any;
  disabledTextStyles?: any;
  disabledCheckBoxStyles?: any;
  labelStyles?: any;
  badgeStyles?: any;
  badgeTextStyles?: any;
  checkBoxStyles?: any;
  save?: 'key' | 'value';
  dropdownShown?: boolean;
  selected?: any[];
}